### ISSUE TITLE
Catmandu-XML 0.15 failes unit tests

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu-XML#16]
With XML::Struct 0.25 or 0.26  installed  Catmandu-XML 0.15 failes the unit test t/importer.t . The code test have success with the XML::Struct 0.23.

    #   Failed test 'simple with depth=1'
    #   at t/importer.t line 14.
    #     Structures begin differing at:
    #          $got->[0]{field2} = ARRAY(0x7fc53352ee30)
    #     $expected->[0]{field2} = HASH(0x7fc533527d18)
    #   Failed test 'multiple entries (disable root)'
    #   at t/importer.t line 14.
    #     Structures begin differing at:
    #          $got->[0]{id} = '1'
    #     $expected->[0]{id} = Does not exist
    # Looks like you failed 2 tests of 15.

perl 5, version 18, subversion 1 (v5.18.1) built for darwin-2level

**Comment by nichtich** [comment]
Fixed in Catmandu-XML 0.16 (with dependency on XML::Struct 0.26)
